language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm run build

script:
  - bash ./deploy-to-gh-pages.sh

env:
  global:
    - GITHUB_REPO: "sagarmahapatra/visaarato-varaaso"
    - GITHUB_TOKEN: "b909f60ce95ab8bd04b5d4c37232169f33606ae5"